apiVersion: v1
kind: Config
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURKekNDQWcrZ0F3SUJBZ0lDQm5Vd0RRWUpLb1pJaHZjTkFRRUxCUUF3TXpFVk1CTUdBMVVFQ2hNTVJHbG4KYVhSaGJFOWpaV0Z1TVJvd0dBWURWUVFERXhGck9ITmhZWE1nUTJ4MWMzUmxjaUJEUVRBZUZ3MHlNakEyTVRBeQpNVEU0TURoYUZ3MDBNakEyTVRBeU1URTRNRGhhTURNeEZUQVRCZ05WQkFvVERFUnBaMmwwWVd4UFkyVmhiakVhCk1CZ0dBMVVFQXhNUmF6aHpZV0Z6SUVOc2RYTjBaWElnUTBFd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUIKRHdBd2dnRUtBb0lCQVFDWFpRT2puMFZXcUVXOTlGZjZXakcvWUU1ZVNOR3dFMWwzRVBva0ZMY0duZW1KY2NNVgpYN3A0V21yaVB2OTdPaTgrMXUvNFM2K3RHUkNYK2FUNm9UMFBJcEtVRWJNQy9wOHV3SmtyMGlEc01lemdhSHF1CnJyem9ENmZHZjZDTWIzcDNmaEt3RHR3S25sVEVZbzZvSGRiUitnczRjVjYweE1NR2lNYUZvVkJnVmZtRTVpckwKZjRNL21LVmZhQUJGT09qRTIyc3N6dk1ONUxMZHdrWnVYemNlbnJjS01HUHdEazBiZmtIS2tqZGZGRVpiMTJUZApJOXIySGU1VTQrd3FSelBWdEVZY0Mram9hRUIvRHhlYkFNMWdhUVlUcU4xQzFiNzNwQlhHWUhjT2l3WThnUDZWCmJZVGtNTVRpUkV2TlloRTFkOXllQmt4b1hvakxSVUdVUUp3MUFnTUJBQUdqUlRCRE1BNEdBMVVkRHdFQi93UUUKQXdJQmhqQVNCZ05WSFJNQkFmOEVDREFHQVFIL0FnRUFNQjBHQTFVZERnUVdCQlJRSnlHR0Vhc3lNOU5aREZmOApBUmtPbHI5Z1d6QU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFOZ3RUcFh3anRydlUvb3pMVEY5MHYvSkI3MlNGCnpxTVp1SGJVTmRkcklDMUl6cDFCN0QrYVY0N2NqdGlqSWcxbmdUTFhIYXZ4SXU3bGdndjhQbG14cmhMSmJvT2kKUjJIb05XRnpiT0QzVjJyMDlJY0xhU3RYcVd5ZkV1OFd0VjlxOXRZL0d6UmZhNnI2VXlTcHEwWTdpVEsrZDYvbQpLbnd2UXFiT2paS0JJdG9xNW9jUXNkamFpVE4zWjdtM3kySmVPTU96VUQ1cWlpWGZMaVJOSzh0cXlVazFZdlhmCkd3TmQ1SHRuaDhnYWtEcnppMkJHU2oyMjNXUnNHRTNUeXRMNytONWRIdGxBY3RqSkJKd1dPRmVLYmZKU0U2TFgKSlAwaXNkMzFQU1ZRNVlOWkVYa01jUGhDZ3djWCtEc05CeDVHVUFvQ0xVaE1PM25jcGpHU09CQjU4dz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://1058ae8c-0276-4418-a5f2-45e379f04279.k8s.ondigitalocean.com
  name: do-nyc1-k8s
contexts:
- context:
    cluster: do-nyc1-k8s
    user: do-nyc1-k8s-admin
  name: do-nyc1-k8s
current-context: do-nyc1-k8s
users:
- name: do-nyc1-k8s-admin
  user:
    token: dop_v1_3b7e44d1eb68221ad9e52a0cd4fec2bd9a3b17af95fb5beb6f1ba7fbddb1ceda
