apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgre
spec:
  replicas: 20
  selector:
    matchLabels:
      app: postgre
  template:
    metadata:
      labels:
        app: postgre
    spec:
      containers:
      - name: postgre
        image: postgres:14.3
        ports:
        - containerPort: 5432
        env: 
        - name: POSTGRES_PASSWORD
          value: "KubeNews*"
        - name: POSTGRES_USER
          value: "kube-news"
        - name: POSTGRES_DB
          value: "kube-news"
---
apiVersion: v1
kind: Service
metadata:
  name: postgre
spec:
  selector:
    app: postgre
  ports:
  - port: 5432
    targetPort: 5432
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-news
spec:
  replicas: 20
  selector:
    matchLabels:
      app: kube-news
  template:
    metadata:
      labels:
        app: kube-news
    spec:
      containers:
      - name: kube-news
        image: otaviomartins/kube-news:v2
        env:
        - name: DB_DATABASE
          value: "kube-news"
        - name: DB_USERNAME
          value: "kube-news"
        - name: DB_PASSWORD
          value: "KubeNews*"
        - name: DB_HOST
          value: "postgre"
---
apiVersion: v1
kind: Service
metadata:
  name: kube-news
spec:
  selector:
    app: kube-news
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30000
  type: NodePort